name: dti_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#How to deploy Prod/Env  google-signin-client_id
#1. change dotenv for change the environment
#2. change the firebase ID on index.html
#3. remove file in macOs (for debug only) : GoogleService-Info and firebase_app_id_file
#4. set flutterfire configure and change the project (this will generate removed file on number 3)
version: 1.1.5+3

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.0
# google_sign_in_web: ^0.11.0
dependencies:
  auto_route: ^7.4.0
  awesome_dialog: ^3.0.2
  bloc: ^8.1.0
  build_web_compilers: ^3.2.7
  camera: ^0.10.3+2
  carousel_slider: ^4.1.1
  country_code_picker: ^3.0.0
  country_codes: ^2.2.0
  country_picker: ^2.0.16
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_table_2: ^2.4.2
  dio: ^5.1.1
  dropdown_search: ^5.0.3
  excel: ^2.0.4
  file_picker: ^5.2.2
  file_saver: ^0.2.8
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flash: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_facebook_auth: ^6.0.1
  flutter_form_builder: ^7.7.0
  flutter_markdown: ^0.6.13
  flutter_material_pickers: ^3.1.4+1
  flutter_screenutil: ^5.5.4
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.1.0
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  getxbottombar: ^0.0.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.4
  group_radio_button: ^1.2.0
  injectable: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  pinput: ^2.2.31
  rating_dialog: ^2.0.4
  shimmer: ^2.0.0
  syncfusion_flutter_pdf: ^21.1.38
  syncfusion_flutter_pdfviewer: ^21.1.38
  syncfusion_flutter_signaturepad: ^21.1.38
  toggle_switch: ^2.0.1
  universal_io: ^2.2.0
  url_launcher: ^6.1.6
  web_browser_detect: ^2.0.3
dev_dependencies:
  auto_route_generator: ^7.1.1

  build_runner: ^2.2.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.4.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - dotenv
    - assets/images/
    - assets/app-store.png
    - assets/google-play.png
    - assets/bubble_chat.webp
    - assets/star.webp
    - assets/images/bg/
    - assets/imgs/
    - assets/imgs/documentpage/
    - assets/icons/
    - assets/files/locations.json
    - assets/corporate/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
