// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkCrB6O_oOyf4ajt3DcEYhckpbDUC0cgo',
    appId: '1:58741229055:web:ff38b87aede41734f153ca',
    messagingSenderId: '58741229055',
    projectId: 'doortoid-mobile',
    authDomain: 'doortoid-mobile.firebaseapp.com',
    storageBucket: 'doortoid-mobile.appspot.com',
    measurementId: 'G-N5Z1Y7YN6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoycEId3dnp5nljjlFibezgdUF8WWynUg',
    appId: '1:58741229055:android:d8306faa6155b58ff153ca',
    messagingSenderId: '58741229055',
    projectId: 'doortoid-mobile',
    storageBucket: 'doortoid-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Tym1o0lWbO5Bo_f6y5oaoLAH58X4ZLI',
    appId: '1:58741229055:ios:b54572a46214a786f153ca',
    messagingSenderId: '58741229055',
    projectId: 'doortoid-mobile',
    storageBucket: 'doortoid-mobile.appspot.com',
    androidClientId: '58741229055-4de80uh73i6a4qfgtlf54duno7j0kg59.apps.googleusercontent.com',
    iosClientId: '58741229055-p66k1t1d82t94vbh8hnlr1a9kusbcjml.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtiWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Tym1o0lWbO5Bo_f6y5oaoLAH58X4ZLI',
    appId: '1:58741229055:ios:b54572a46214a786f153ca',
    messagingSenderId: '58741229055',
    projectId: 'doortoid-mobile',
    storageBucket: 'doortoid-mobile.appspot.com',
    androidClientId: '58741229055-4de80uh73i6a4qfgtlf54duno7j0kg59.apps.googleusercontent.com',
    iosClientId: '58741229055-p66k1t1d82t94vbh8hnlr1a9kusbcjml.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtiWeb',
  );
}
