// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4MmQZXUiJEjGm_-o-Xt7DTwJPB8Ibz0',
    appId: '1:450417909901:web:6cc0c1e23a4fc7dd4802c4',
    messagingSenderId: '450417909901',
    projectId: 'doortoid',
    authDomain: 'doortoid.firebaseapp.com',
    storageBucket: 'doortoid.appspot.com',
    measurementId: 'G-95DJF06G3P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7NcdJBi22_oVprNTLiopDGarUro5Ap8',
    appId: '1:450417909901:ios:913e3b5c469a3e334802c4',
    messagingSenderId: '450417909901',
    projectId: 'doortoid',
    storageBucket: 'doortoid.appspot.com',
    androidClientId: '450417909901-5msdj2kaitidico3mt0pacn1v7c2noiu.apps.googleusercontent.com',
    iosClientId: '450417909901-l2lbkpfrjft1bv6vretqq1id0td51qrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtiWeb',
  );
}
